[2025-05-01T00:38:53.867+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:38:53.878+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:38:53.879+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 5
[2025-05-01T00:38:53.894+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): download_and_unzip_locally> on 2025-04-30 23:04:13.923792+00:00
[2025-05-01T00:38:53.899+0000] {standard_task_runner.py:60} INFO - Started process 21009 to run task
[2025-05-01T00:38:53.902+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'download_and_unzip_locally', 'manual__2025-04-30T23:04:13.923792+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpgwjb0_99']
[2025-05-01T00:38:53.904+0000] {standard_task_runner.py:88} INFO - Job 187: Subtask download_and_unzip_locally
[2025-05-01T00:38:54.054+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T23:04:13.923792+00:00 [running]> on host e4f2445a264f
[2025-05-01T00:38:54.250+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='download_and_unzip_locally' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:04:13.923792+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:04:13.923792+00:00'
[2025-05-01T00:38:54.937+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 83, in download_and_unzip_locally
    with open(zip_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/01-05-2025_capitalbikeshare-tripdata.zip'
[2025-05-01T00:38:54.962+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=download_and_unzip_locally, execution_date=20250430T230413, start_date=20250501T003853, end_date=20250501T003854
[2025-05-01T00:38:54.979+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 187 for task download_and_unzip_locally ([Errno 2] No such file or directory: '/opt/airflow/dags/data/01-05-2025_capitalbikeshare-tripdata.zip'; 21009)
[2025-05-01T00:38:54.998+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-01T00:38:55.038+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
