[2025-04-30T19:47:05.433+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.unzip_file manual__2025-04-30T19:20:03.145231+00:00 [queued]>
[2025-04-30T19:47:05.446+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.unzip_file manual__2025-04-30T19:20:03.145231+00:00 [queued]>
[2025-04-30T19:47:05.447+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-04-30T19:47:05.465+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): unzip_file> on 2025-04-30 19:20:03.145231+00:00
[2025-04-30T19:47:05.472+0000] {standard_task_runner.py:60} INFO - Started process 3675 to run task
[2025-04-30T19:47:05.484+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'unzip_file', 'manual__2025-04-30T19:20:03.145231+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmptgurnv6x']
[2025-04-30T19:47:05.488+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask unzip_file
[2025-04-30T19:47:05.663+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.unzip_file manual__2025-04-30T19:20:03.145231+00:00 [running]> on host e4f2445a264f
[2025-04-30T19:47:05.905+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='unzip_file' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T19:20:03.145231+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T19:20:03.145231+00:00'
[2025-04-30T19:47:05.907+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 71, in unzip_file
    with ZipFile(io.BytesIO(zip_bytes), 'r') as zip_ref:
TypeError: a bytes-like object is required, not 'str'
[2025-04-30T19:47:05.941+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=bikeshare_etl_pipeline, task_id=unzip_file, execution_date=20250430T192003, start_date=20250430T194705, end_date=20250430T194705
[2025-04-30T19:47:05.959+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task unzip_file (a bytes-like object is required, not 'str'; 3675)
[2025-04-30T19:47:05.976+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T19:47:06.024+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
