[2025-05-01T00:26:15.125+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:26:15.143+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:26:15.144+0000] {taskinstance.py:2193} INFO - Starting attempt 22 of 22
[2025-05-01T00:26:15.169+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_cleaned_data_to_minio> on 2025-04-30 23:04:13.923792+00:00
[2025-05-01T00:26:15.178+0000] {standard_task_runner.py:60} INFO - Started process 20007 to run task
[2025-05-01T00:26:15.183+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'load_cleaned_data_to_minio', 'manual__2025-04-30T23:04:13.923792+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpgprhvlwc']
[2025-05-01T00:26:15.187+0000] {standard_task_runner.py:88} INFO - Job 171: Subtask load_cleaned_data_to_minio
[2025-05-01T00:26:15.351+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [running]> on host e4f2445a264f
[2025-05-01T00:26:15.632+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_cleaned_data_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:04:13.923792+00:00' AIRFLOW_CTX_TRY_NUMBER='22' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:04:13.923792+00:00'
[2025-05-01T00:26:15.669+0000] {base.py:83} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2025-05-01T00:26:15.670+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2025-05-01T00:26:15.685+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 186, in load_cleaned_data_to_minio
    "endpoint_url": credentials.endpoint_url,
AttributeError: 'ReadOnlyCredentials' object has no attribute 'endpoint_url'
[2025-05-01T00:26:15.749+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=bikeshare_etl_pipeline, task_id=load_cleaned_data_to_minio, execution_date=20250430T230413, start_date=20250501T002615, end_date=20250501T002615
[2025-05-01T00:26:15.769+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 171 for task load_cleaned_data_to_minio ('ReadOnlyCredentials' object has no attribute 'endpoint_url'; 20007)
[2025-05-01T00:26:15.799+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-01T00:26:15.850+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
