[2025-05-01T00:25:01.511+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
