[2025-05-01T00:33:42.055+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:33:42.071+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [queued]>
[2025-05-01T00:33:42.072+0000] {taskinstance.py:2193} INFO - Starting attempt 25 of 26
[2025-05-01T00:33:42.097+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_cleaned_data_to_minio> on 2025-04-30 23:04:13.923792+00:00
[2025-05-01T00:33:42.106+0000] {standard_task_runner.py:60} INFO - Started process 20581 to run task
[2025-05-01T00:33:42.111+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'load_cleaned_data_to_minio', 'manual__2025-04-30T23:04:13.923792+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpuvd2e4_m']
[2025-05-01T00:33:42.115+0000] {standard_task_runner.py:88} INFO - Job 174: Subtask load_cleaned_data_to_minio
[2025-05-01T00:33:42.293+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.load_cleaned_data_to_minio manual__2025-04-30T23:04:13.923792+00:00 [running]> on host e4f2445a264f
[2025-05-01T00:33:42.527+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_cleaned_data_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:04:13.923792+00:00' AIRFLOW_CTX_TRY_NUMBER='25' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:04:13.923792+00:00'
[2025-05-01T00:33:42.552+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 176, in load_cleaned_data_to_minio
    df = pl.read_parquet(output_file)
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/_utils/deprecation.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/io/parquet/functions.py", line 209, in read_parquet
    return lf.collect()
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/lazyframe/frame.py", line 2053, in collect
    return wrap_df(ldf.collect(callback))
FileNotFoundError: No such file or directory (os error 2): 30-04-2025/capitalbikeshare-tripdata.parquet
[2025-05-01T00:33:42.597+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=load_cleaned_data_to_minio, execution_date=20250430T230413, start_date=20250501T003342, end_date=20250501T003342
[2025-05-01T00:33:42.612+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 174 for task load_cleaned_data_to_minio (No such file or directory (os error 2): 30-04-2025/capitalbikeshare-tripdata.parquet; 20581)
[2025-05-01T00:33:42.645+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-01T00:33:42.695+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
