[2025-04-30T22:59:41.637+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T22:59:41.654+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T22:59:41.655+0000] {taskinstance.py:2193} INFO - Starting attempt 11 of 12
[2025-04-30T22:59:41.672+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): upload_files_to_minio> on 2025-04-30 22:38:47.303758+00:00
[2025-04-30T22:59:41.676+0000] {standard_task_runner.py:60} INFO - Started process 14011 to run task
[2025-04-30T22:59:41.681+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'upload_files_to_minio', 'manual__2025-04-30T22:38:47.303758+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp9wzkuz9s']
[2025-04-30T22:59:41.683+0000] {standard_task_runner.py:88} INFO - Job 117: Subtask upload_files_to_minio
[2025-04-30T22:59:41.826+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.upload_files_to_minio manual__2025-04-30T22:38:47.303758+00:00 [running]> on host e4f2445a264f
[2025-04-30T22:59:42.062+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='upload_files_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T22:38:47.303758+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T22:38:47.303758+00:00'
[2025-04-30T22:59:42.065+0000] {logging_mixin.py:188} INFO - None
[2025-04-30T22:59:42.065+0000] {logging_mixin.py:188} INFO - None
[2025-04-30T22:59:42.066+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 107, in upload_files_to_minio
    local_path = os.path.join(folder_path, csv_file)
  File "/usr/local/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-04-30T22:59:42.100+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=upload_files_to_minio, execution_date=20250430T223847, start_date=20250430T225941, end_date=20250430T225942
[2025-04-30T22:59:42.138+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 117 for task upload_files_to_minio (expected str, bytes or os.PathLike object, not NoneType; 14011)
[2025-04-30T22:59:42.173+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T22:59:42.230+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
