[2025-04-30T22:38:54.139+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T22:38:54.158+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T22:38:47.303758+00:00 [queued]>
[2025-04-30T22:38:54.160+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-04-30T22:38:54.188+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): download_and_unzip_locally> on 2025-04-30 22:38:47.303758+00:00
[2025-04-30T22:38:54.196+0000] {standard_task_runner.py:60} INFO - Started process 12704 to run task
[2025-04-30T22:38:54.202+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bikeshare_etl_pipeline', 'download_and_unzip_locally', 'manual__2025-04-30T22:38:47.303758+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmppwrz5agp']
[2025-04-30T22:38:54.205+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask download_and_unzip_locally
[2025-04-30T22:38:54.570+0000] {task_command.py:423} INFO - Running <TaskInstance: bikeshare_etl_pipeline.download_and_unzip_locally manual__2025-04-30T22:38:47.303758+00:00 [running]> on host e4f2445a264f
[2025-04-30T22:38:54.859+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='adedoyinsamuel25@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bikeshare_etl_pipeline' AIRFLOW_CTX_TASK_ID='download_and_unzip_locally' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T22:38:47.303758+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T22:38:47.303758+00:00'
[2025-04-30T22:38:55.658+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 81, in download_and_unzip_locally
    with open(zip_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/aairflow/dags/data/30-04-2025_capitalbikeshare-tripdata.zip'
[2025-04-30T22:38:55.741+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=bikeshare_etl_pipeline, task_id=download_and_unzip_locally, execution_date=20250430T223847, start_date=20250430T223854, end_date=20250430T223855
[2025-04-30T22:38:55.785+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task download_and_unzip_locally ([Errno 2] No such file or directory: '/opt/aairflow/dags/data/30-04-2025_capitalbikeshare-tripdata.zip'; 12704)
[2025-04-30T22:38:55.821+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-30T22:38:55.896+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
